# Site settings
title: Hacking Health Camp
email: s.letelie@hackinghealth.ca
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/hhcamp_wip" # the subpath of your site, e.g. /blog/
url: http://alsacedigitale.github.io
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

arguments:
  developer: "Transform everyday healthcare challenges into real solutions. Work on meaningful problems. Help improve healthcare. Get connected, and practice your skills."
  designer: "Connect to create holistic solutions with patients, not for patients. Work on meaningful problems. Help improve healthcare. Get connected, and practice your skills."
  professional: "Collaborate with tech experts to solve problems in healthcare. Let your ideas inspire practical solutions."

events:
  - name: Future of Health
    verb: Inspire
    date: "Thursday, March 19th, 9:30 AM - 5 PM"
    venue: Auditorium du conservatoire de musique - 1 place Dauphine - Strasbourg
    description: A entire day of inspiring and forward-thinking conferences on the future of health by a line up of internationally-recognized health mentors.
  - name: Health Pitch Challenge
    verb: Bonus
    date: "Thursday, March 19th, 7:00 PM - 10:00 PM"
    venue: Auditorium du conservatoire de musique - 1 place Dauphine - Strasbourg
    description: "A festive event dedicated to health startups, complete with the presence of investors. Early-stage startups will pitch; attendees will vote by investing in their favorite startups with fake banknotes. The winner will be the one who raises the most money."
  - name: Health Data Day
    verb: Learn
    date: "Friday, March 20th, 9:00 AM - 5:00 PM"
    venue: Forum de la faculté de médecine - 1 rue Humann - Strasbourg
    description: "A full day of workshops and conferences centered around the technical, medical, privacy and legal aspects of producing, consuming and analyse health data."
  - name: Health Hackathon
    verb: "Learn"
    date: "Friday, March 20th, 5:00 PM to Sunday, March 8:00 PM"
    venue: Forum de la faculté de médecine - 1 rue Humann - Strasbourg
    description: "The second annual hackathon will run from Friday evening to Sunday evening. Health professionals, developers and designers will create prototypes based on challenges submitted before the event."

testimonies:
  developer:
    name: Yann Klis
    title: Developer since 4 years in novembre agency
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec rutrum nunc. Vestibulum venenatis posuere est eget tincidunt. Donec eleifend justo et lacus convallis mollis. Vivamus eget ultricies ante. Suspendisse potenti. Cras in metus sit amet sapien luctus dapibus non sed tortor."
    quote: "Cras nec mollis tellus. Sed eget ultricies mi. Fusce ex ante, iaculis ac lectus vel, dignissim ornare sem."
    twitter: yannski
    linkedin: in/yannklis
  designer:
    name: Franck Bevaudan
    title: Developer since 4 years in novembre agency
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec rutrum nunc. Vestibulum venenatis posuere est eget tincidunt. Donec eleifend justo et lacus convallis mollis. Vivamus eget ultricies ante. Suspendisse potenti. Cras in metus sit amet sapien luctus dapibus non sed tortor."
    quote: "Cras nec mollis tellus. Sed eget ultricies mi. Fusce ex ante, iaculis ac lectus vel, dignissim ornare sem."
  professional:
    name: Franck Bevaudan
    title: Developer since 4 years in novembre agency
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec rutrum nunc. Vestibulum venenatis posuere est eget tincidunt. Donec eleifend justo et lacus convallis mollis. Vivamus eget ultricies ante. Suspendisse potenti. Cras in metus sit amet sapien luctus dapibus non sed tortor."
    quote: "Cras nec mollis tellus. Sed eget ultricies mi. Fusce ex ante, iaculis ac lectus vel, dignissim ornare sem."

people:
  team:
    - name: "Team Hacking Health"
      list:
        - name: Sébastien Letélié
          twitter: sebmade
          linkedin: in/sebmade
        - name: Johan Moreau
          twitter: johan_moreau
          linkedin: profile/view?id=8416769
        - name: Lionel Brosius
          twitter: LionelBrosius
          linkedin: profile/view?id=10032998
        - name: Anna Ferrere
          twitter: AnnaFERRERE
          linkedin: profile/view?id=89971225
        - name: Dan Del Balso
          twitter: Dan_DelBalso
          linkedin: profile/view?id=115316082
        - name: Stéphane Becker
          twitter: whirly
          linkedin: profile/view?id=6334744
        - name: Emeline Hahn
          linkedin: profile/view?id=116408008
        - name: Bruno Rakotozafy
          twitter: BruRakoto
        - name: Jeremy Kieger
          linkedin: profile/view?id=196711421
        - name: Caroline Boehrer
        - name: Marilyne Oswald
          linkedin: profile/view?id=23540355
        - name: Imen Chaabouni
          linkedin: profile/view?id=177694139
        - name: Yann Klis
          twitter: yannski
          linkedin: yannklis
        - name: Sandrine Hilaire
          linkedin: profile/view?id=48205645
        - name: Yannick Jost
          twitter: yanjost
          linkedin: profile/view?id=27757141
        - name: Emmanuelle Ebel
          linkedin: profile/view?id=47963402
        - name: Catherine Mosser
        - name: Sébastien Lorentz
          linkedin: profile/view?id=237706210
        - name: Clara Reb
          linkedin: pub/clara-reb/58/935/4b2
        - name: Léa Frickert
          linkedin: profile/view?id=325954665
        - name: Elodie Marchand
          linkedin: pub/elodie-marchand/5a/334/a7b
        - name: Marion Ripplinger
          linkedin: pub/marion-ripplinger/a4/772/6a3
        - name: Isabelle Lusseyran
          linkedin: profile/view?id=45618053
        - name: Chloé Peccatte
          linkedin: profile/view?id=29282572
  future-of-health:
    - name: "Speakers"
      list:
        - name: Uwe Diegel
          description: iHealth founder
          twitter: uwe
          linkedin: in/uwediegel
        - name: Pierre-Paul Vidal
          description: MD PhD
          linkedin: profile/view?id=151969844
        - name: Jorge Juan Fernandez Garcia
          description: BHITE polymath (Biomedicine + Healthcare + Innovation + Technology + Entrepreneurship)
          twitter: jorgejuan
          linkedin: profile/view?id=2277954
        - name: Jacques Marescaux
          description: ""
        - name: Zayna Khayat
          description: "At MaRS, Zayna and her rockstar team help smooth the path to adoption of health innovation by healthcare systems in Ontario and around the world. She is also an adjunct faculty with the Rotman School of Management in the Health Sector Strategy stream."
          twitter: ZaynaKhayat
          linkedin: in/zkhayat
        - name: To be announced soon
        - name: To be announced soon
        - name: To be announced soon
  health-data-day:
    - name: "Speakers"
      list:
        - name: Mike Amundsen
          description: "Director of API Architecture, API Academy at CA Technologies || Working to improve the quality and usability of information on the Web."
          twitter: mamund
          linkedin: in/mamund
        - name: Pierre Desmarais
          description: "Avocat au Barreau de Paris et Correspondant Informatique et Libertés (CIL), Pierre Desmarais exerce une activité de conseil en droit de la santé et des nouvelles technologies. Il accompagne au quotidien des start-ups développant des produits et services innovants dans le domaine de la santé, de l’opendata et de l’e-santé. Il est également chargé d’enseignement au Conservatoire National des Arts et Métiers (CNAM) et à l'Université Paris VIII."
          twitter: DesmaraisPierre
          linkedin: profile/view?id=88478484
        - name: Louis Lyu
          description: "iHealthLabs CTO - Head developer of iHealth API"
          twitter:
          linkedin:
        - name: Sofie van der Meulen
          description: "At Axon lawyers Sofie specializes in EU and national legal and regulatory issues relating to medical devices, with a special focus on medical software, big data & data protection."
          twitter: DeltalexLegal
          linkedin: in/sofievandermeulen
  health-hackathon:
    - name: "Jury"
      list:
        - name: To be announced soon !
        - name: To be announced soon !
        - name: To be announced soon !
        - name: To be announced soon !
    - name: "Mentors"
      list:
        - name: Elalami Lafkih
          description: Pretotyping expert
          twitter: e_lalami
          linkedin: profile/view?id=36725748
        - name: Pierre Desmarais
          description: "Avocat au Barreau de Paris et Correspondant Informatique et Libertés (CIL), Pierre Desmarais exerce une activité de conseil en droit de la santé et des nouvelles technologies. Il accompagne au quotidien des start-ups développant des produits et services innovants dans le domaine de la santé, de l’opendata et de l’e-santé. Il est également chargé d’enseignement au Conservatoire National des Arts et Métiers (CNAM) et à l'Université Paris VIII."
          twitter: DesmaraisPierre
          linkedin: profile/view?id=88478484
        - name: Caroline Zorn
          description: Health lawyer
          twitter: c_zorn
          linkedin: in/carolinezorn/en
        - name: Guillaume Lours
          description: Agile coach
          twitter: glours
          linkedin: profile/view?id=45301585

schedules:
  future-of-health:
    - title: "19th"
      subtitle: "THURSDAY, MARCH"
      list:
        - title: "9:30am - 10am"
          description: "Introduction"
        - title: "10am - 10:30am"
          description: "Zayna Khayat"
        - title: "10:30am - 11am"
          description: "Uwe Diegel"
        - title: "11am - 11:30am"
          description: "Pierre-Paul Vidal"
        - title: "11:30am - 12am"
          description: "Jorge Juan Fernandez Garcia"
        - title: "12am - 2pm"
          description: "Lunch"
        - title: "2pm - 2:30am"
          description: "Jacques Marescaux"
        - title: "2:30pm - 3pm"
          description: "To be announced soon"
        - title: "3pm - 3:30pm"
          description: "To be announced soon"
        - title: "3:30pm - 4pm"
          description: "To be announced soon"
  health-pitch-challenge:
    - title: "19th"
      subtitle: "THURSDAY, MARCH"
      list:
        - title: "7pm"
          description: "Admission"
        - title: "8pm - 8:15pm"
          description: "Introduction"
        - title: "8:20pm"
          description: "5' for each startup to present"
        - title: "9pm"
          description: "Votes"
        - title: "9:30pm"
          description: "Results"
  health-data-day:
    - title: "20th"
      subtitle: "FRIDAY, MARCH"
      list:
        - title: "8:45am - 9:15am"
          description: "Admission"
        - title: "9:15am - 10am"
          description: "Keynote"
        - title: "10am - 10:30am"
          description: "Mike Amundsen - demystify API"
        - title: "10:30am - 11am"
          description: "Pierre Desmarais"
        - title: "11am - 11:30am"
          description: "To be announced soon"
        - title: "11:30am - 12am"
          description: "To be announced soon"
        - title: "10am - 11am"
          description: "Louis Lyu - iHealthLabs workshop"
        - title: "11am - 12am"
          description: "To be announced soon"
        - title: "12am - 2pm"
          description: "Lunch"
        - title: "2pm - 2:30pm"
          description: "Sofie van der Meulen - Legal aspects of big data analytics in healthcare"
        - title: "2:30pm - 3pm"
          description: "To be announced soon"
        - title: "3pm - 3:30am"
          description: "To be announced soon"
        - title: "3:30pm - 4pm"
          description: "To be announced soon"
        - title: "4pm - 4:30pm"
          description: "To be announced soon"
        - title: "4:30pm - 5pm"
          description: "To be announced soon"
        - title: "2pm - 3pm"
          description: "To be announced soon"
        - title: "3pm - 4pm"
          description: "To be announced soon"
  health-hackathon:
    - title: "20th"
      subtitle: "FRIDAY, MARCH"
      list:
        - title: "5pm"
          description: "Admission"
        - title: "5pm - 6pm"
          description: "Pitch Clinic : pitch session training"
        - title: "7pm"
          description: "Introduction"
        - title: "7:20pm"
          description: "Coachs presentation"
        - title: "7:30pm"
          description: "Pitch : 1' to present your challenge"
        - title: "9pm"
          description: "Diner, team building, start working"
        - title: "9:30pm"
          description: "First crazy night"
    - title: "21st"
      subtitle: "SATURDAY, MARCH"
      list:
        - title: "8am"
          description: "Breakfast"
        - title: "12am"
          description: "Lunch"
        - title: "5pm"
          description: "Demo clinics : pitch training session and review"
        - title: "7pm"
          description: "Diner"
        - title: "10pm"
          description: "Second crazy night"
    - title: "22nd"
      subtitle: "SUNDAY, MARCH"
      list:
        - title: "8am"
          description: "Breakfast"
        - title: "12am"
          description: "Lunch and coachs meetings"
        - title: "2:30pm"
          description: "Jury arrivals"
        - title: "3pm"
          description: "Closing session"
        - title: "3:30pm"
          description: "Prototype presentations: 3' demo + 2' questions & answers"
        - title: "6:30pm"
          description: "Jury deliberation"
        - title: "7pm"
          description: "Prizes"
        - title: "8pm"
          description: "Last drink"

question_and_answers:
  main:
    - question: "Donec dapibus id massa"
      answer: "Une superbe réponse"
  health-hackathon:
    - question: "Donec dapibus id massa"
      answer: "Une superbe réponse"
    - question: "Donec dapibus id massa"
      answer: "Une superbe réponse"
    - question: "Donec dapibus id massa"
      answer: "Une superbe réponse"
    - question: "Donec dapibus id massa"
      answer: "Une superbe réponse"
    - question: "Donec dapibus id massa"
      answer: "Une superbe réponse"

hardwaresoftware:
  - image: "pipo.jpg"
    title: "Lorem Ipsum"
    description: "Parnters provides..."
    link: "http://www.google.fr"
    link_title: "Download documentation"
  - image: "pipo2.jpg"
    title: "Lorem Ipsum 2"
    description: "Parnters provides..."
    link: "http://www.google2.fr"
    link_title: "View website"

social_links:
  facebook: http://facebook.com/digitalhealthcamp
  twitter: https://twitter.com/digitalhealthcp
  linkedin: http://www.linkedin.com/groups/DigitalHealthCamp-6400524
  google-plus: https://plus.google.com/u/1/b/116340191957345593804/116340191957345593804/posts
  youtube: https://www.youtube.com/channel/UCviq99fD7Pu5kuNItesUfEg
partners:
  gold:
    - name: iHealth
      url: http://www.ihealthlabs.eu/en/
    - name: Allianz
      url: http://www.allianz.com/
    - name: Strasbourg
      url: http://strasbourg.eu
  silver:
    - name: GE Healthcare
      url: http://www3.gehealthcare.com/en/global_gateway
    - name: Doctissimo
      url: http://www.doctissimo.fr
    - name: ASIP Santé
      url: http://esante.gouv.fr/asip-sante
    - name: Inforoute Santé Canada
      url: https://www.infoway-inforoute.ca/index.php
    - name: Région Alsace
      url: http://www.region-alsace.eu
  bronze:
    - name: icanopée
      url: http://www.icanopee.fr/index.php/fr/
    - name: IHU
      url: http://www.ihu-strasbourg.eu/ihu/
  regular:
    - name: ARS
      url: http://www.ars.alsace.sante.fr/Internet.alsace.0.html
    - name: Alsace Biovalley
      url: http://www.alsace-biovalley.com/
    - name: Alsace eSanté
      url: https://www.sante-alsace.fr/cms
    - name: Health 2.0
      url: http://www.health2con.com/
    - name: Epitech
      url: http://www.epitech.eu/
    - name: Hack your phd
      url: http://hackyourphd.org/
    - name: VIDAL
      url: http://www.vidal.fr/
    - name: wellfundr
      url: http://wellfundr.com/
    - name: TheFamily
      url: http://thefamily.co/
    - name: bwcon
      url: http://bwcon.de/
    - name: FI-Ware
      url: http://www.fi-ware.org/
    - name: ECHAlliance
      url: http://www.echalliance.com/
    - name: etalab
      url: http://www.etalab.gouv.fr/
    - name: CNR SANTÉ
      url: http://www.cnr-sante.fr/
    - name: CCI Alsace
      url: http://www.alsace.cci.fr/
    - name: Club JADE
      url: http://www.club-jade.fr/
    - name: Alsace Innovation
      url: http://www.alsaceinnovation.eu/
    - name: TICBioMed
      url: http://www.ticbiomed.org/
    - name: Samsung
      url: http://www.samsung.com
    - name: LeaderHealth
      url: http://www.leaderhealth.ch
    - name: Syntec Numérique
      url: http://www.syntec-numerique.fr/
  media:
    - name: BUZZ-ESANTE
      url: http://buzz-esante.com/
    - name: DNA
      url: http://www.dna.fr
    - name: France3 Alsace
      url: https://www.france3.fr/
    - name: HealthITSpace
      url: http://www.healthitspace.eu/
    - name: eHealthNews
      url: http://www.ehealthnews.eu/
    - name: OSOZ
      url: http://www.osoz.pl/
    - name: TIC Santé
      url: http://www.tic-sante.fr
    - name: SIH Solutions
      url: http://www.sih-solutions.fr/

last_event_videos:
  - name: shazam du medicament
    url: http://www.youtube.com/embed/JroXpVOFXho
  - name: project1
    url: http://www.youtube.com/embed/vlOuNpgrGd8
  - name: project3
    url: http://www.youtube.com/embed/pQGF-ts2gAw
  - name: project6
    url: http://www.youtube.com/embed/_6OUmMgoZPw
  - name: project7
    url: http://www.youtube.com/embed/petu8o3NnvA
  - name: project8
    url: http://www.youtube.com/embed/jOjgvoQPlFg
  - name: project12
    url: http://www.youtube.com/embed/dOZXIsyfpyw
  - name: project14
    url: http://www.youtube.com/embed/mu4kwEcF7LA
  - name: project19
    url: http://www.youtube.com/embed/E2HLwXOmRGk
  - name: project20
    url: http://www.youtube.com/embed/PYcbs817M8w
  - name: project23
    url: http://www.youtube.com/embed/k7DWYWvQ0rc
  - name: project24
    url: http://www.youtube.com/embed/rnPABtGyfc4
  - name: project25
    url: http://www.youtube.com/embed/L2SVd4DRF34
  - name: project29
    url: http://www.youtube.com/embed/MiFo_HOcWoA
  - name: project31
    url: http://www.youtube.com/embed/EFhyYTip72E
  - name: project34
    url: http://www.youtube.com/embed/5plX2H6QC7A
  - name: project35
    url: http://www.youtube.com/embed/TAwbkZeI1FA
  - name: project36
    url: http://www.youtube.com/embed/zGT2RxA7jAU
