# Site settings
title: Hacking Health Camp
email: s.letelie@hackinghealth.ca
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/hhcamp_wip" # the subpath of your site, e.g. /blog/
url: http://alsacedigitale.github.io
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

arguments:
  developer: "Transform everyday healthcare challenges into real solutions. Work on meaningful problems. Help improve healthcare. Get connected, and practice your skills."
  designer: "Connect to create holistic solutions with patients, not for patients. Work on meaningful problems. Help improve healthcare. Get connected, and practice your skills."
  professional: "Collaborate with tech experts to solve problems in healthcare. Let your ideas inspire practical solutions."

events:
  - name: Future of Health
    verb: Inspire
    date: "Thursday, March 19th, 9:30 AM - 5 PM"
    venue: Auditorium du conservatoire de musique - 1 place Dauphine - Strasbourg
    description: A entire day of inspiring and forward-thinking conferences on the future of health by a line up of internationally-recognized health mentors.
  - name: Health Pitch Challenge
    verb: Bonus
    date: "Thursday, March 19th, 7:00 PM - 10:00 PM"
    venue: Auditorium du conservatoire de musique - 1 place Dauphine - Strasbourg
    description: "A festive event dedicated to health startups, complete with the presence of investors. Early-stage startups will pitch; attendees will vote by investing in their favorite startups with fake banknotes. The winner will be the one who raises the most money."
  - name: Health Data Day
    verb: Learn
    date: "Friday, March 20th, 9:00 AM - 5:00 PM"
    venue: Forum de la faculté de médecine - 1 rue Humann - Strasbourg
    description: "A full day of workshops and conferences centered around the technical, medical, privacy and legal aspects of producing, consuming and analyse health data."
  - name: Health Hackathon
    verb: "Learn"
    date: "Friday, March 20th, 5:00 PM to Sunday, March 8:00 PM"
    venue: Forum de la faculté de médecine - 1 rue Humann - Strasbourg
    description: "The second annual hackathon will run from Friday evening to Sunday evening. Health professionals, developers and designers will create prototypes based on challenges submitted before the event."
social_links:
  facebook: http://facebook.com/digitalhealthcamp
  twitter: https://twitter.com/digitalhealthcp
  linkedin: http://www.linkedin.com/groups/DigitalHealthCamp-6400524
  google-plus: https://plus.google.com/u/1/b/116340191957345593804/116340191957345593804/posts
  youtube: https://www.youtube.com/channel/UCviq99fD7Pu5kuNItesUfEg
team_members:
  - name: Sébastien Letélié
    twitter: sebmade
    linkedin: in/sebmade
  - name: Johan Moreau
    twitter: johan_moreau
    linkedin: profile/view?id=8416769
  - name: Lionel Brosius
    twitter: LionelBrosius
    linkedin: profile/view?id=10032998
  - name: Anna Ferrere
    twitter: AnnaFERRERE
    linkedin: profile/view?id=89971225
  - name: Dan Del Baso
    twitter: Dan_DelBalso
    linkedin: profile/view?id=115316082
  - name: Stéphane Becker
    twitter: whirly
    linkedin: profile/view?id=6334744
  - name: Emeline Hahn
    linkedin: profile/view?id=116408008
  - name: Bruno Rakotozafy
    twitter: BruRakoto
  - name: Jeremy Kieger
    linkedin: profile/view?id=196711421
  - name: Caroline Boehrer
  - name: Marilyne Oswald
    linkedin: profile/view?id=23540355
  - name: Imen Chaabouni
    linkedin: profile/view?id=177694139
  - name: Yann Klis
    twitter: yannski
    linkedin: yannklis
  - name: Sandrine Hilaire
    linkedin: profile/view?id=48205645
  - name: Yannick Jost
    twitter: yanjost
    linkedin: profile/view?id=27757141
  - name: Emmanuelle Ebel
    linkedin: profile/view?id=47963402
  - name: Catherine Mosser
  - name: Sébastien Lorentz
    linkedin: profile/view?id=237706210
  - name: Clara Reb
    linkedin: pub/clara-reb/58/935/4b2
  - name: Léa Frickert
    linkedin: profile/view?id=325954665
  - name: Elodie Marchand
    linkedin: pub/elodie-marchand/5a/334/a7b
  - name: Marion Ripplinger
    linkedin: pub/marion-ripplinger/a4/772/6a3
  - name: Isabelle Lusseyrand
    linkedin: profile/view?id=45618053
  - name: Chloé Peccatte
    linkedin: profile/view?id=29282572
partners:
  gold:
    - name: iHealth
      url:
    - name: Allianz
      url:
    - name: Strasbourg
      url: http://strasbourg.eu
  silver:
    - name: GE Healthcare
      url:
    - name: ASIP Santé
      url:
    - name: Inforoute Santé Canada
      url:
    - name: Région Alsace
      url: http://www.region-alsace.eu
  bronze:
    - name: icanopée
      url:
    - name: IHU
      url:
  regular:
    - name: ARS
      url:
    - name: Alsace Biovalley
      url:
    - name: Alsace eSanté
      url:
    - name: Health 2.0
      url:
    - name: Epitech
      url:
    - name: Hack your phd
      url:
    - name: VIDAL
      url:
    - name: wellfundr
      url:
    - name: TheFamily
      url: http://thefamily.co/
    - name: bwcon
      url:
    - name: FI-Ware
      url: ECHAlliance
    - name: etalab
      url:
  media:
    - name: BUZZ-ESANTE
      url:
    - name: DNA
      url: http://www.dna.fr
    - name: France3 Alsace
      url:
