# Site settings
title: Hacking Health Camp
email: s.letelie@hackinghealth.ca
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.hackinghealth.camp"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

events:
  future: Future of Health
  pitch: Health Pitch Challenge
  dataday: Health Data Day
  hackathon: Health Hackathon
social_links:
  facebook: http://facebook.com/digitalhealthcamp
  twitter: https://twitter.com/digitalhealthcp
  linkedin: http://www.linkedin.com/groups/DigitalHealthCamp-6400524
  google-plus: https://plus.google.com/u/1/b/116340191957345593804/116340191957345593804/posts
  youtube: https://www.youtube.com/channel/UCviq99fD7Pu5kuNItesUfEg
team_members:
  - name: Sébastien Letélié
    twitter: sebmade
    linkedin: in/sebmade
  - name: Johan Moreau
    twitter: johan_moreau
    linkedin: profile/view?id=8416769
  - name: Lionel Brosius
    twitter: LionelBrosius
    linkedin: profile/view?id=10032998
  - name: Anna Ferrere
    twitter: AnnaFERRERE
    linkedin: profile/view?id=89971225
  - name: Dan Del Baso
    twitter: Dan_DelBalso
    linkedin: profile/view?id=115316082
  - name: Stéphane Becker
    twitter: whirly
    linkedin: profile/view?id=6334744
  - name: Emeline Hahn
    linkedin: profile/view?id=116408008
  - name: Bruno Rakotozafy
    twitter: BruRakoto
  - name: Jeremy Kieger
    linkedin: profile/view?id=196711421
  - name: Caroline Boehrer
  - name: Marilyne Oswald
    linkedin: profile/view?id=23540355
  - name: Imen Chaabouni
    linkedin: profile/view?id=177694139
  - name: Yann Klis
    twitter: yannski
    linkedin: yannklis
  - name: Sandrine Hilaire
    linkedin: profile/view?id=48205645
  - name: Yannick Jost
    twitter: yanjost
    linkedin: profile/view?id=27757141
  - name: Emmanuelle Ebel
    linkedin: profile/view?id=47963402
  - name: Catherine Mosser
  - name: Sébastien Lorentz
    linkedin: profile/view?id=237706210
  - name: Clara Reb
    linkedin: pub/clara-reb/58/935/4b2
  - name: Léa Frickert
    linkedin: profile/view?id=325954665
  - name: Elodie Marchand
    linkedin: pub/elodie-marchand/5a/334/a7b
  - name: Marion Ripplinger
    linkedin: pub/marion-ripplinger/a4/772/6a3
  - name: Isabelle Lusseyrand
    linkedin: profile/view?id=45618053
  - name: Chloé Peccatte
    linkedin: profile/view?id=29282572

